language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=2.0.7
  - SYMFONY_VERSION=2.1.*
  - SYMFONY_VERSION=dev-master

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar require symfony/symfony:${SYMFONY_VERSION} --dev

script: phpunit --coverage-text
